@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1168118672 { 
   	label=NotifieurCourriel
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   NotifieurCourriel1168118672[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NotifieurCourriel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   serviceName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- enregistrerDansFichier(nomFichier: String, contenu: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ enregistrerEvenement(type: String, message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- enregistrerNotification(type: String, notification: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ envoyerNotification(message: String, destinataire: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1520686321 { 
   	label=ExamenElementaire
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ExamenElementaire1520686321[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ExamenElementaire</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datePrescription: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   parametres: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1689656849 { 
   	label=Medecin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Medecin1689656849[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Medecin</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   courriel: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   matricule: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prenom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telephone: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1778634442 { 
   	label=DemandeRDV
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DemandeRDV1778634442[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DemandeRDV</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   date: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   examen: Examen [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   medecin: Medecin [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numero: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   patient: Patient [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2094708099 { 
   	label=CentreDeSoin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   CentreDeSoin2094708099[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CentreDeSoin</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adresse: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   courriel: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   demandesRDV: List&lt;DemandeRDV&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   examens: List&lt;Examen&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gestionnaireNotifications: GestionnaireNotifications [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   laboratoires: List&lt;Laboratoire&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   medecins: List&lt;Medecin&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   patients: List&lt;Patient&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prescriptions: List&lt;Prescription&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telephone: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ RecevoirResultatExamen(patient: Patient, medecin: Medecin, examens: List&lt;Examen&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterDemandeRDV(demande: DemandeRDV)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterExamen(examen: Examen)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterLaboratoire(laboratoire: Laboratoire)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterMedecin(medecin: Medecin)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterPatient(patient: Patient)</TD></TR>
<TR><TD ALIGN="LEFT" >+ ajouterPrescription(prescription: Prescription)</TD></TR>
<TR><TD ALIGN="LEFT" >+ attributionRDV(reponse: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ charger(): CentreDeSoin</TD></TR>
<TR><TD ALIGN="LEFT" >- choisirLaboratoire(examen: Examen): Laboratoire</TD></TR>
<TR><TD ALIGN="LEFT" >+ creerPrescription(patient: Patient, medecin: Medecin, examens: List&lt;Examen&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ envoyerDemandeRDV(demande: DemandeRDV)</TD></TR>
<TR><TD ALIGN="LEFT" >+ envoyerResultatExamen(demande: DemandeRDV)</TD></TR>
<TR><TD ALIGN="LEFT" >+ resultatExamen(resultat: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ sauvegarder()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2139992360 { 
   	label=GestionnaireNotifications
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   GestionnaireNotifications2139992360[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GestionnaireNotifications</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   notifieurs: List&lt;Notifieur&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ajouterNotifieur(notifieur: Notifieur)</TD></TR>
<TR><TD ALIGN="LEFT" >+ enregistrerEvenement(type: String, message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ notifier(event: String, destinataires: List&lt;String&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_221942223 { 
   	label=SimulateurLaboratoire
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SimulateurLaboratoire221942223[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SimulateurLaboratoire</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ envoyerResultatExamen(resultat: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ generateRandomDate(): LocalDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ repondreDemandeRDV(reponse: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ traiterExamens(centre: CentreDeSoin)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main2390489[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- afficherContenuFichier(nomFichier: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- afficherContenuFichier(nomFichier: String, filtre: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- afficherResultats()</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_250347688 { 
   	label=GestionnaireDonnees
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   GestionnaireDonnees250347688[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GestionnaireDonnees</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ chargerDonnees(): Object</TD></TR>
<TR><TD ALIGN="LEFT" >+ sauvegarderDonnees(donnees: Object)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_270813002 { 
   	label=ExamenCompose
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ExamenCompose270813002[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ExamenCompose</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   datePrescription: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   examens: List&lt;ExamenElementaire&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_624621626 { 
   	label=Prescription
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Prescription624621626[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Prescription</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   date: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   examens: List&lt;Examen&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numero: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_835200208 { 
   	label=NotifieurSMS
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   NotifieurSMS835200208[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NotifieurSMS</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   serviceName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- enregistrerDansFichier(nomFichier: String, contenu: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ enregistrerEvenement(type: String, message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- enregistrerNotification(type: String, notification: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ envoyerNotification(message: String, destinataire: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_873235173 { 
   	label=Patient
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Patient873235173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Patient</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   code: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   courriel: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prenom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telephone: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_885978032 { 
   	label=Laboratoire
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Laboratoire885978032[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Laboratoire</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adresse: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   code: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   courriel: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   examensDisponibles: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nom: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telephone: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ envoyerResultatExamen(resultat: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ peutFaireExamen(examen: Examen): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ recevoirDemandeRDV(demande: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
CentreDeSoin2094708099 -> DemandeRDV1778634442[label="demandesRDV
[0..*]"];
CentreDeSoin2094708099 -> ExamenCompose270813002[arrowhead=none];
CentreDeSoin2094708099 -> ExamenElementaire1520686321[arrowhead=none];
CentreDeSoin2094708099 -> GestionnaireNotifications2139992360[label="gestionnaireNotifications
[0..1]"];
CentreDeSoin2094708099 -> Laboratoire885978032[label="laboratoires
[0..*]"];
CentreDeSoin2094708099 -> Medecin1689656849[label="medecins
[0..*]"];
CentreDeSoin2094708099 -> Patient873235173[label="patients
[0..*]"];
CentreDeSoin2094708099 -> Prescription624621626[label="prescriptions
[0..*]"];
GestionnaireNotifications2139992360 -> NotifieurCourriel1168118672[arrowhead=none];
GestionnaireNotifications2139992360 -> NotifieurSMS835200208[arrowhead=none];
Main2390489 -> SimulateurLaboratoire221942223[label="main() -> traiterExamens()"];
    
}
@enduml